name: Run Selenium IDE Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options:
          --shm-size 2g

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g selenium-side-runner mocha mochawesome mochawesome-merge mochawesome-report-generator

    - name: Convert Selenium IDE tests to Mocha
      run: selenium-side-runner --output-directory=./mocha-tests ./Test_CICD.side

    - name: Run Mocha tests
      run: mocha ./mocha-tests --reporter mochawesome --reporter-options reportDir=./results,reportFilename=mochawesome-report

    - name: Merge and generate mochawesome report
      run: |
        npx mochawesome-merge ./results/*.json > ./results/mochawesome.json
        npx mochawesome-report-generator ./results/mochawesome.json -o ./results

    - name: Upload raw test results
      uses: actions/upload-artifact@v3
      with:
        name: raw-test-results
        path: ./results

    - name: Upload detailed test report
      uses: actions/upload-artifact@v3
      with:
        name: detailed-test-report
        path: ./results
